[package]
name = "tome-client"
version = "0.1.0"
edition = "2024"
readme = "../README.md"
repository = "https://github.com/Zeviraty/TOME"
license-file = "../LICENSE"

[dependencies]
console_engine = { version = "2.6.1", features = ["form"] }
crossterm = "0.26.1"
rand = "0.9.2"
