name: Docker Image CI

on:
  push:
    branches: ["*"]  # Run on all branches
    tags: ['v*.*.*'] # Still run on version tags

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag or fallback to nightly
      id: meta
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "tagged=true" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tags=zevvi/tome:$VERSION" >> "$GITHUB_OUTPUT"
        elif [[ "${GITHUB_REF}" == refs/heads/main ]]; then
          echo "tagged=false" >> "$GITHUB_OUTPUT"
          echo "version=main" >> "$GITHUB_OUTPUT"
          echo "tags=zevvi/tome:latest" >> "$GITHUB_OUTPUT"
        else
          DATE=$(date +%Y%m%d)
          echo "tagged=false" >> "$GITHUB_OUTPUT"
          echo "version=nightly-$DATE" >> "$GITHUB_OUTPUT"
          echo "tags=zevvi/tome:nightly,zevvi/tome:nightly-$DATE" >> "$GITHUB_OUTPUT"
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
