name: Makefile CI

on:
  push:
    branches: [ "*" ]
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: configure chmod
      run: chmod +x ./configure

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Create tarball
      run: make dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./TOME.tar.gz

    - name: Upload Release Asset
      run: |
        echo "Uploading release..."
        gh release create $GITHUB_REF ./TOME.tar.gz --title "Release $GITHUB_REF" --notes "Release notes for $GITHUB_REF"

